language: python

python:
  - '3.7.6'


before_script:
  - pip3 install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="PurBeurre_project.settings.travis"

services:
  - postgresql

# safelist
branches:
  only:
    - staging

script:
  - cd PurBeurre_project pytest -v -m "not api_request and not selenium_mk"