language: python

python:

  - '3.7.6'


before_script:

  - pip3 install -r PurBeurreApp/requirements.txt


env: DJANGO_SETTINGS_MODULE="PurBeurre_project.settings.travis"


services:

  - postgresql

# safelist
branches:
  only:
    - staging

script:

  - pytest -v -m "not api_request and not selenium_mk"